### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [Bildungsportal/moodle-local_aise#2]
Hello,

According to Moodle standards, all plugin functions should include frankenstyle prefix to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)

Function aise_like() in the lib.php file should be renamed to local_aise_like().
![image](https://github.com/user-attachments/assets/8b78402e-b7e2-43fe-9e7e-47320ba9986c)

**Comment by rschrenk** [comment]
issue solved and uploaded new release to [moodle.org/plugins/local_aise](https://moodle.org/plugins/local_aise/)
